# Resolução baseada na resolução do Summer de Instrução Luá
# source: https://trybecourse.slack.com/archives/C02TH6V3MC5/p1657298198437299

FROM node:16-alpine
WORKDIR /app
COPY . .
RUN npm install
CMD ["npm", "start"]
EXPOSE 3000